print('a' == 'b')
print('a' == 'a')
print('-----------------')
print('Ab'.lower() == 'ab'.lower())
print('Ab'.lower() == 'aC'.lower())
print('-----------------')
print(1 == 1)
print(1 != 1)
print(1 > 1)
print(1 < 1)
print(1 >= 1)
print(1 <= 1)
print('-----------------')
print(1 == 1 and 3 != 1)
print(1 == 1 and 3 == 1)
print('-----------------')
list = [1,2,3]
print(3 in list)
print(5 in list)